export interface Product {
  _id: string;
  name: string;
  sku: string;
  slug: string;
  brand: string;
  category: string;
  subCategory: string;
  mrp: number;
  sellingPrice: number;
  discount?: number;
  taxClass?: string;
  stockQty: number;
  lowStockThreshold?: number;
  stockStatus: "in_stock" | "out_of_stock";
  mainImage?: string;
  detailImage?: string;
  galleryImages?: string[];
  sold?: number;        
  revenue?: number;     
  lastSoldAt?: string; 
  status?: "active" | "draft" | "disabled";
  visibility?: "public" | "private";
  description?: string;
  metaTitle?: string;
  metaDescription?: string;
  metaKeywords?: string;
  vendorId?: string;
  createdBy?: string;
  updatedBy?: string;
  createdAt?: string;
  updatedAt?: string;
}
